//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.05 at 02:04:48 PM CET 
//


package uzuzjmd.api_services.synonyms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="w" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="p" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="r" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "w"
})
@XmlRootElement(name = "words")
public class Words {

    protected List<Words.W> w;

    /**
     * Gets the value of the w property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the w property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getW().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Words.W }
     * 
     * 
     */
    public List<Words.W> getW() {
        if (w == null) {
            w = new ArrayList<Words.W>();
        }
        return this.w;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="p" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="r" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class W {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "p")
        protected String p;
        @XmlAttribute(name = "r")
        protected String r;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the p property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP() {
            return p;
        }

        /**
         * Sets the value of the p property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP(String value) {
            this.p = value;
        }

        /**
         * Gets the value of the r property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getR() {
            return r;
        }

        /**
         * Sets the value of the r property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setR(String value) {
            this.r = value;
        }

    }

}
