
package uzuzjmd.service.competence.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * Wed Feb 26 14:16:33 CET 2014
 * Generated source version: 3.0.0-milestone2
 */

@XmlRootElement(name = "getCompetencesResponse", namespace = "http://competence.service.uzuzjmd/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCompetencesResponse", namespace = "http://competence.service.uzuzjmd/")

public class GetCompetencesResponse {

    @XmlElement(name = "return")
    private uzuzjmd.rcd.generated.Rdceo[] _return;

    public uzuzjmd.rcd.generated.Rdceo[] getReturn() {
        return this._return;
    }

    public void setReturn(uzuzjmd.rcd.generated.Rdceo[] new_return)  {
        this._return = new_return;
    }

}

