package uzuzjmd.competence.assessment.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import uzuzjmd.competence.assessment.model.ReflexionsAssessment;
import uzuzjmd.competence.assessment.service.ReflexionsAssessmentLocalServiceUtil;

/**
 * The extended model base implementation for the ReflexionsAssessment service. Represents a row in the &quot;competenceAssessment_ReflexionsAssessment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReflexionsAssessmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReflexionsAssessmentImpl
 * @see uzuzjmd.competence.assessment.model.ReflexionsAssessment
 * @generated
 */
public abstract class ReflexionsAssessmentBaseImpl
    extends ReflexionsAssessmentModelImpl implements ReflexionsAssessment {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a reflexions assessment model instance should use the {@link ReflexionsAssessment} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ReflexionsAssessmentLocalServiceUtil.addReflexionsAssessment(this);
        } else {
            ReflexionsAssessmentLocalServiceUtil.updateReflexionsAssessment(this);
        }
    }
}
