package uzuzjmd.competence.assessment.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import uzuzjmd.competence.assessment.model.UserLearningTemplateMap;
import uzuzjmd.competence.assessment.service.UserLearningTemplateMapLocalServiceUtil;

/**
 * The extended model base implementation for the UserLearningTemplateMap service. Represents a row in the &quot;competenceAssessment_UserLearningTemplateMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserLearningTemplateMapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserLearningTemplateMapImpl
 * @see uzuzjmd.competence.assessment.model.UserLearningTemplateMap
 * @generated
 */
public abstract class UserLearningTemplateMapBaseImpl
    extends UserLearningTemplateMapModelImpl implements UserLearningTemplateMap {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a user learning template map model instance should use the {@link UserLearningTemplateMap} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            UserLearningTemplateMapLocalServiceUtil.addUserLearningTemplateMap(this);
        } else {
            UserLearningTemplateMapLocalServiceUtil.updateUserLearningTemplateMap(this);
        }
    }
}
