function competence_webapp(){var cb='',_=' top: -1000px;',zb='" for "gwt:onLoadErrorFn"',xb='" for "gwt:onPropertyErrorFn"',ib='");',Ab='#',bc='.cache.js',Cb='/',Ib='//',Wb='09841380853A7E62B587D977615BD95B',Xb='4F40374C23641D007A8416177A56EC90',Yb='703C9C9E196A9F99B55B0A06715453C5',Zb='928BDDCCBDBECCC4BE8BB3EE4FBA78FF',ac=':',rb='::',tc=':moduleBase',bb='<!doctype html>',db='<html><head><\/head><body><\/body><\/html>',ub='=',Bb='?',$b='B75328ABF0134F4A49DECBB7A8E2FAE6',wb='Bad handler "',_b='C925FFA91DBE9C1413C8FDCDF3A6C249',ab='CSS1Compat',gb='Chrome',fb='DOMContentLoaded',W='DUMMY',hc='GwtExt.css',sc='Ignoring non-whitelisted Dev Mode URL: ',rc='__gwtDevModeHook:competence_webapp',qc='_gwt_dummy_',Hb='base',Fb='baseUrl',R='begin',X='body',Q='bootstrap',Eb='clear.cache.gif',U='competence_webapp',Vb='competence_webapp.devmode.js',Gb='competence_webapp.nocache.js',qb='competence_webapp::',tb='content',ic='css/bootstrap.min.css',kc='css/font-awesome.min.css',jc='css/gwt-bootstrap.css',nc='end',hb='eval("',pc='file:',Rb='gecko',Sb='gecko1_8',S='gwt.codesvr.competence_webapp=',T='gwt.codesvr=',lc='gwt/clean/clean.css',mc='gwt/standard/standard.css',yb='gwt:onLoadErrorFn',vb='gwt:onPropertyErrorFn',sb='gwt:property',nb='head',fc='href',oc='http:',Ob='ie10',Qb='ie8',Pb='ie9',Y='iframe',Db='img',kb='javascript',Z='javascript:""',cc='link',gc='loadExternalRefs',ob='meta',mb='moduleRequested',lb='moduleStartup',Nb='msie',pb='name',Kb='opera',$='position:absolute; width:0; height:0; border:none; left: -1000px;',dc='rel',Mb='safari',jb='script',Ub='selectingPermutation',V='startup',ec='stylesheet',eb='undefined',Tb='unknown',Jb='user.agent',Lb='webkit';var o=window;var p=document;r(Q,R);function q(){var a=o.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:U,sessionId:o.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
competence_webapp.__sendStats=r;competence_webapp.__moduleName=U;competence_webapp.__errFn=null;competence_webapp.__moduleBase=W;competence_webapp.__softPermutationId=0;competence_webapp.__computePropValue=null;competence_webapp.__getPropMap=null;competence_webapp.__gwtInstallCode=function(){};competence_webapp.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[U]={moduleName:U};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(X)[0]}
function B(){if(v){return}var a=p.createElement(Y);a.src=Z;a.id=U;a.style.cssText=$+_;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==ab?bb:cb;v.write(b+db);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==eb){return typeof p.body!=eb&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(fb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(fb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(hb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(ib));g=f.createElement(jb);g.language=kb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(jb);g.language=kb;g.text=c[i];e.appendChild(g);d(e,g)}}}
competence_webapp.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;p.getElementsByTagName(nb)[0].appendChild(n)}
competence_webapp.__startLoadingFragment=function(a){return G(a)};competence_webapp.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(jb);c.language=kb;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(ob);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(pb),k;if(j){j=j.replace(qb,cb);if(j.indexOf(rb)>=0){continue}if(j==sb){k=i.getAttribute(tb);if(k){var l,m=k.indexOf(ub);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=cb}c[j]=l}}else if(j==vb){k=i.getAttribute(tb);if(k){try{d=eval(k)}catch(a){alert(wb+k+xb)}}}else if(j==yb){k=i.getAttribute(tb);if(k){try{e=eval(k)}catch(a){alert(wb+k+zb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;competence_webapp.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Ab);if(b==-1){b=a.length}var c=a.indexOf(Bb);if(c==-1){c=a.length}var d=a.lastIndexOf(Cb,Math.min(c,b));return d>=0?a.substring(0,d+1):cb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Db);b.src=a+Eb;a=e(b.src)}return a}
function g(){var a=t(Fb);if(a!=null){return a}return cb}
function h(){var a=p.getElementsByTagName(jb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Gb)!=-1){return e(a[b].src)}}return cb}
function i(){var a=p.getElementsByTagName(Hb);if(a.length>0){return a[a.length-1].href}return cb}
function j(){var a=p.location;return a.href==a.protocol+Ib+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==cb){k=h()}if(k==cb){k=i()}if(k==cb&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return competence_webapp.__moduleBase+a}
function H(){var f=[];var g=0;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Jb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Kb)!=-1}())return Kb;if(function(){return b.indexOf(Lb)!=-1}())return Mb;if(function(){return b.indexOf(Nb)!=-1&&p.documentMode>=10}())return Ob;if(function(){return b.indexOf(Nb)!=-1&&p.documentMode>=9}())return Pb;if(function(){return b.indexOf(Nb)!=-1&&p.documentMode>=8}())return Qb;if(function(){return b.indexOf(Rb)!=-1}())return Sb;return Tb};i[Jb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,opera:4,safari:5};s=function(a,b){return b in i[a]};competence_webapp.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};competence_webapp.__computePropValue=k;o.__gwt_activeModules[U].bindings=competence_webapp.__getPropMap;r(Q,Ub);if(q()){return G(Vb)}var l;try{h([Ob],Wb);h([Kb],Xb);h([Sb],Yb);h([Pb],Zb);h([Qb],$b);h([Mb],_b);l=f[k(Jb)];var m=l.indexOf(ac);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}competence_webapp.__softPermutationId=g;return G(l+bc)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(cc);b.setAttribute(dc,ec);b.setAttribute(fc,G(a));p.getElementsByTagName(nb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(gc,R);c(hc);c(ic);c(jc);c(kc);c(lc);c(mc);r(gc,nc)}
D();competence_webapp.__moduleBase=F();u[U].moduleBase=competence_webapp.__moduleBase;var J=H();if(o){var K=!!(o.location.protocol==oc||o.location.protocol==pc);o.__gwt_activeModules[U].canRedirect=K;function L(){var b=qc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=rc;var N=o.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(sc+N)}N=cb}if(N&&!o[M]){o[M]=true;o[M+tc]=F();var O=p.createElement(jb);O.src=N;var P=p.getElementsByTagName(nb)[0];P.insertBefore(O,P.firstElementChild||P.children[0]);return false}}}I();r(Q,nc);C(J);return true}
competence_webapp.succeeded=competence_webapp();