//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 01:58:00 AM CET 
//


package org.w3._2002._07.owl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnotationPropertyRange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnotationPropertyRange">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/2002/07/owl#}AnnotationAxiom">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.w3.org/2002/07/owl#}AnnotationProperty"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.w3.org/2002/07/owl#}IRI"/>
 *           &lt;element ref="{http://www.w3.org/2002/07/owl#}AbbreviatedIRI"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotationPropertyRange", propOrder = {
    "annotationProperty",
    "iri",
    "abbreviatedIRI"
})
public class AnnotationPropertyRange
    extends AnnotationAxiom
{

    @XmlElement(name = "AnnotationProperty", required = true)
    protected AnnotationProperty annotationProperty;
    @XmlElement(name = "IRI")
    protected IRI iri;
    @XmlElement(name = "AbbreviatedIRI")
    protected AbbreviatedIRI abbreviatedIRI;

    /**
     * Gets the value of the annotationProperty property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationProperty }
     *     
     */
    public AnnotationProperty getAnnotationProperty() {
        return annotationProperty;
    }

    /**
     * Sets the value of the annotationProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationProperty }
     *     
     */
    public void setAnnotationProperty(AnnotationProperty value) {
        this.annotationProperty = value;
    }

    /**
     * Gets the value of the iri property.
     * 
     * @return
     *     possible object is
     *     {@link IRI }
     *     
     */
    public IRI getIRI() {
        return iri;
    }

    /**
     * Sets the value of the iri property.
     * 
     * @param value
     *     allowed object is
     *     {@link IRI }
     *     
     */
    public void setIRI(IRI value) {
        this.iri = value;
    }

    /**
     * Gets the value of the abbreviatedIRI property.
     * 
     * @return
     *     possible object is
     *     {@link AbbreviatedIRI }
     *     
     */
    public AbbreviatedIRI getAbbreviatedIRI() {
        return abbreviatedIRI;
    }

    /**
     * Sets the value of the abbreviatedIRI property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbbreviatedIRI }
     *     
     */
    public void setAbbreviatedIRI(AbbreviatedIRI value) {
        this.abbreviatedIRI = value;
    }

}
