//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 01:58:00 AM CET 
//


package org.w3._2002._07.owl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Class complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Class">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/2002/07/owl#}ClassExpression">
 *       &lt;attribute name="IRI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="abbreviatedIRI" type="{http://www.w3.org/2002/07/owl#}abbreviatedIRI" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Class")
public class Class
    extends ClassExpression
{

    @XmlAttribute(name = "IRI")
    @XmlSchemaType(name = "anyURI")
    protected String iri;
    @XmlAttribute(name = "abbreviatedIRI")
    protected String abbreviatedIRI;

    /**
     * Gets the value of the iri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIRI() {
        return iri;
    }

    /**
     * Sets the value of the iri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIRI(String value) {
        this.iri = value;
    }

    /**
     * Gets the value of the abbreviatedIRI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbbreviatedIRI() {
        return abbreviatedIRI;
    }

    /**
     * Sets the value of the abbreviatedIRI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbbreviatedIRI(String value) {
        this.abbreviatedIRI = value;
    }

}
