//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 01:58:00 AM CET 
//


package org.w3._2002._07.owl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataUnionOf complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataUnionOf">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/2002/07/owl#}DataRange">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.w3.org/2002/07/owl#}DataRange" maxOccurs="unbounded" minOccurs="2"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataUnionOf", propOrder = {
    "dataRange"
})
public class DataUnionOf
    extends DataRange
{

    @XmlElements({
        @XmlElement(name = "Datatype", type = Datatype.class),
        @XmlElement(name = "DataIntersectionOf", type = DataIntersectionOf.class),
        @XmlElement(name = "DataUnionOf", type = DataUnionOf.class),
        @XmlElement(name = "DataComplementOf", type = DataComplementOf.class),
        @XmlElement(name = "DataOneOf", type = DataOneOf.class),
        @XmlElement(name = "DatatypeRestriction", type = DatatypeRestriction.class)
    })
    protected List<DataRange> dataRange;

    /**
     * Gets the value of the dataRange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataRange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Datatype }
     * {@link DataIntersectionOf }
     * {@link DataUnionOf }
     * {@link DataComplementOf }
     * {@link DataOneOf }
     * {@link DatatypeRestriction }
     * 
     * 
     */
    public List<DataRange> getDataRange() {
        if (dataRange == null) {
            dataRange = new ArrayList<DataRange>();
        }
        return this.dataRange;
    }

}
