//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 01:58:00 AM CET 
//


package org.w3._2002._07.owl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataComplementOf complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataComplementOf">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/2002/07/owl#}DataRange">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.w3.org/2002/07/owl#}DataRange"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataComplementOf", propOrder = {
    "datatype",
    "dataIntersectionOf",
    "dataUnionOf",
    "dataComplementOf",
    "dataOneOf",
    "datatypeRestriction"
})
public class DataComplementOf
    extends DataRange
{

    @XmlElement(name = "Datatype")
    protected Datatype datatype;
    @XmlElement(name = "DataIntersectionOf")
    protected DataIntersectionOf dataIntersectionOf;
    @XmlElement(name = "DataUnionOf")
    protected DataUnionOf dataUnionOf;
    @XmlElement(name = "DataComplementOf")
    protected DataComplementOf dataComplementOf;
    @XmlElement(name = "DataOneOf")
    protected DataOneOf dataOneOf;
    @XmlElement(name = "DatatypeRestriction")
    protected DatatypeRestriction datatypeRestriction;

    /**
     * Gets the value of the datatype property.
     * 
     * @return
     *     possible object is
     *     {@link Datatype }
     *     
     */
    public Datatype getDatatype() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datatype }
     *     
     */
    public void setDatatype(Datatype value) {
        this.datatype = value;
    }

    /**
     * Gets the value of the dataIntersectionOf property.
     * 
     * @return
     *     possible object is
     *     {@link DataIntersectionOf }
     *     
     */
    public DataIntersectionOf getDataIntersectionOf() {
        return dataIntersectionOf;
    }

    /**
     * Sets the value of the dataIntersectionOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataIntersectionOf }
     *     
     */
    public void setDataIntersectionOf(DataIntersectionOf value) {
        this.dataIntersectionOf = value;
    }

    /**
     * Gets the value of the dataUnionOf property.
     * 
     * @return
     *     possible object is
     *     {@link DataUnionOf }
     *     
     */
    public DataUnionOf getDataUnionOf() {
        return dataUnionOf;
    }

    /**
     * Sets the value of the dataUnionOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataUnionOf }
     *     
     */
    public void setDataUnionOf(DataUnionOf value) {
        this.dataUnionOf = value;
    }

    /**
     * Gets the value of the dataComplementOf property.
     * 
     * @return
     *     possible object is
     *     {@link DataComplementOf }
     *     
     */
    public DataComplementOf getDataComplementOf() {
        return dataComplementOf;
    }

    /**
     * Sets the value of the dataComplementOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataComplementOf }
     *     
     */
    public void setDataComplementOf(DataComplementOf value) {
        this.dataComplementOf = value;
    }

    /**
     * Gets the value of the dataOneOf property.
     * 
     * @return
     *     possible object is
     *     {@link DataOneOf }
     *     
     */
    public DataOneOf getDataOneOf() {
        return dataOneOf;
    }

    /**
     * Sets the value of the dataOneOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataOneOf }
     *     
     */
    public void setDataOneOf(DataOneOf value) {
        this.dataOneOf = value;
    }

    /**
     * Gets the value of the datatypeRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link DatatypeRestriction }
     *     
     */
    public DatatypeRestriction getDatatypeRestriction() {
        return datatypeRestriction;
    }

    /**
     * Sets the value of the datatypeRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatatypeRestriction }
     *     
     */
    public void setDatatypeRestriction(DatatypeRestriction value) {
        this.datatypeRestriction = value;
    }

}
