//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 01:58:00 AM CET 
//


package org.w3._2002._07.owl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InverseObjectProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InverseObjectProperties">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/2002/07/owl#}ObjectPropertyAxiom">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.w3.org/2002/07/owl#}ObjectPropertyExpression" maxOccurs="2" minOccurs="2"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InverseObjectProperties", propOrder = {
    "objectPropertyExpression"
})
public class InverseObjectProperties
    extends ObjectPropertyAxiom
{

    @XmlElements({
        @XmlElement(name = "ObjectProperty", type = ObjectProperty.class),
        @XmlElement(name = "ObjectInverseOf", type = ObjectInverseOf.class)
    })
    protected List<ObjectPropertyExpression> objectPropertyExpression;

    /**
     * Gets the value of the objectPropertyExpression property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectPropertyExpression property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectPropertyExpression().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectProperty }
     * {@link ObjectInverseOf }
     * 
     * 
     */
    public List<ObjectPropertyExpression> getObjectPropertyExpression() {
        if (objectPropertyExpression == null) {
            objectPropertyExpression = new ArrayList<ObjectPropertyExpression>();
        }
        return this.objectPropertyExpression;
    }

}
