//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 01:58:00 AM CET 
//


package org.w3._2002._07.owl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NegativeDataPropertyAssertion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NegativeDataPropertyAssertion">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/2002/07/owl#}Assertion">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.w3.org/2002/07/owl#}DataPropertyExpression"/>
 *         &lt;group ref="{http://www.w3.org/2002/07/owl#}Individual"/>
 *         &lt;element ref="{http://www.w3.org/2002/07/owl#}Literal"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NegativeDataPropertyAssertion", propOrder = {
    "dataProperty",
    "namedIndividual",
    "anonymousIndividual",
    "literal"
})
public class NegativeDataPropertyAssertion
    extends Assertion
{

    @XmlElement(name = "DataProperty", required = true)
    protected DataProperty dataProperty;
    @XmlElement(name = "NamedIndividual")
    protected NamedIndividual namedIndividual;
    @XmlElement(name = "AnonymousIndividual")
    protected AnonymousIndividual anonymousIndividual;
    @XmlElement(name = "Literal", required = true)
    protected Literal literal;

    /**
     * Gets the value of the dataProperty property.
     * 
     * @return
     *     possible object is
     *     {@link DataProperty }
     *     
     */
    public DataProperty getDataProperty() {
        return dataProperty;
    }

    /**
     * Sets the value of the dataProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataProperty }
     *     
     */
    public void setDataProperty(DataProperty value) {
        this.dataProperty = value;
    }

    /**
     * Gets the value of the namedIndividual property.
     * 
     * @return
     *     possible object is
     *     {@link NamedIndividual }
     *     
     */
    public NamedIndividual getNamedIndividual() {
        return namedIndividual;
    }

    /**
     * Sets the value of the namedIndividual property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedIndividual }
     *     
     */
    public void setNamedIndividual(NamedIndividual value) {
        this.namedIndividual = value;
    }

    /**
     * Gets the value of the anonymousIndividual property.
     * 
     * @return
     *     possible object is
     *     {@link AnonymousIndividual }
     *     
     */
    public AnonymousIndividual getAnonymousIndividual() {
        return anonymousIndividual;
    }

    /**
     * Sets the value of the anonymousIndividual property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnonymousIndividual }
     *     
     */
    public void setAnonymousIndividual(AnonymousIndividual value) {
        this.anonymousIndividual = value;
    }

    /**
     * Gets the value of the literal property.
     * 
     * @return
     *     possible object is
     *     {@link Literal }
     *     
     */
    public Literal getLiteral() {
        return literal;
    }

    /**
     * Sets the value of the literal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Literal }
     *     
     */
    public void setLiteral(Literal value) {
        this.literal = value;
    }

}
