//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 01:58:00 AM CET 
//


package org.w3._2002._07.owl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectAllValuesFrom complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectAllValuesFrom">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/2002/07/owl#}ClassExpression">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.w3.org/2002/07/owl#}ObjectPropertyExpression"/>
 *         &lt;group ref="{http://www.w3.org/2002/07/owl#}ClassExpression"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectAllValuesFrom", propOrder = {
    "objectProperty",
    "objectInverseOf",
    "clazz",
    "objectIntersectionOf",
    "objectUnionOf",
    "objectComplementOf",
    "objectOneOf",
    "objectSomeValuesFrom",
    "objectAllValuesFrom",
    "objectHasValue",
    "objectHasSelf",
    "objectMinCardinality",
    "objectMaxCardinality",
    "objectExactCardinality",
    "dataSomeValuesFrom",
    "dataAllValuesFrom",
    "dataHasValue",
    "dataMinCardinality",
    "dataMaxCardinality",
    "dataExactCardinality"
})
public class ObjectAllValuesFrom
    extends ClassExpression
{

    @XmlElement(name = "ObjectProperty")
    protected ObjectProperty objectProperty;
    @XmlElement(name = "ObjectInverseOf")
    protected ObjectInverseOf objectInverseOf;
    @XmlElement(name = "Class")
    protected Class clazz;
    @XmlElement(name = "ObjectIntersectionOf")
    protected ObjectIntersectionOf objectIntersectionOf;
    @XmlElement(name = "ObjectUnionOf")
    protected ObjectUnionOf objectUnionOf;
    @XmlElement(name = "ObjectComplementOf")
    protected ObjectComplementOf objectComplementOf;
    @XmlElement(name = "ObjectOneOf")
    protected ObjectOneOf objectOneOf;
    @XmlElement(name = "ObjectSomeValuesFrom")
    protected ObjectSomeValuesFrom objectSomeValuesFrom;
    @XmlElement(name = "ObjectAllValuesFrom")
    protected ObjectAllValuesFrom objectAllValuesFrom;
    @XmlElement(name = "ObjectHasValue")
    protected ObjectHasValue objectHasValue;
    @XmlElement(name = "ObjectHasSelf")
    protected ObjectHasSelf objectHasSelf;
    @XmlElement(name = "ObjectMinCardinality")
    protected ObjectMinCardinality objectMinCardinality;
    @XmlElement(name = "ObjectMaxCardinality")
    protected ObjectMaxCardinality objectMaxCardinality;
    @XmlElement(name = "ObjectExactCardinality")
    protected ObjectExactCardinality objectExactCardinality;
    @XmlElement(name = "DataSomeValuesFrom")
    protected DataSomeValuesFrom dataSomeValuesFrom;
    @XmlElement(name = "DataAllValuesFrom")
    protected DataAllValuesFrom dataAllValuesFrom;
    @XmlElement(name = "DataHasValue")
    protected DataHasValue dataHasValue;
    @XmlElement(name = "DataMinCardinality")
    protected DataMinCardinality dataMinCardinality;
    @XmlElement(name = "DataMaxCardinality")
    protected DataMaxCardinality dataMaxCardinality;
    @XmlElement(name = "DataExactCardinality")
    protected DataExactCardinality dataExactCardinality;

    /**
     * Gets the value of the objectProperty property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectProperty }
     *     
     */
    public ObjectProperty getObjectProperty() {
        return objectProperty;
    }

    /**
     * Sets the value of the objectProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectProperty }
     *     
     */
    public void setObjectProperty(ObjectProperty value) {
        this.objectProperty = value;
    }

    /**
     * Gets the value of the objectInverseOf property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectInverseOf }
     *     
     */
    public ObjectInverseOf getObjectInverseOf() {
        return objectInverseOf;
    }

    /**
     * Sets the value of the objectInverseOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectInverseOf }
     *     
     */
    public void setObjectInverseOf(ObjectInverseOf value) {
        this.objectInverseOf = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link Class }
     *     
     */
    public Class getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Class }
     *     
     */
    public void setClazz(Class value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the objectIntersectionOf property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectIntersectionOf }
     *     
     */
    public ObjectIntersectionOf getObjectIntersectionOf() {
        return objectIntersectionOf;
    }

    /**
     * Sets the value of the objectIntersectionOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectIntersectionOf }
     *     
     */
    public void setObjectIntersectionOf(ObjectIntersectionOf value) {
        this.objectIntersectionOf = value;
    }

    /**
     * Gets the value of the objectUnionOf property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectUnionOf }
     *     
     */
    public ObjectUnionOf getObjectUnionOf() {
        return objectUnionOf;
    }

    /**
     * Sets the value of the objectUnionOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectUnionOf }
     *     
     */
    public void setObjectUnionOf(ObjectUnionOf value) {
        this.objectUnionOf = value;
    }

    /**
     * Gets the value of the objectComplementOf property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectComplementOf }
     *     
     */
    public ObjectComplementOf getObjectComplementOf() {
        return objectComplementOf;
    }

    /**
     * Sets the value of the objectComplementOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectComplementOf }
     *     
     */
    public void setObjectComplementOf(ObjectComplementOf value) {
        this.objectComplementOf = value;
    }

    /**
     * Gets the value of the objectOneOf property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectOneOf }
     *     
     */
    public ObjectOneOf getObjectOneOf() {
        return objectOneOf;
    }

    /**
     * Sets the value of the objectOneOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectOneOf }
     *     
     */
    public void setObjectOneOf(ObjectOneOf value) {
        this.objectOneOf = value;
    }

    /**
     * Gets the value of the objectSomeValuesFrom property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectSomeValuesFrom }
     *     
     */
    public ObjectSomeValuesFrom getObjectSomeValuesFrom() {
        return objectSomeValuesFrom;
    }

    /**
     * Sets the value of the objectSomeValuesFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectSomeValuesFrom }
     *     
     */
    public void setObjectSomeValuesFrom(ObjectSomeValuesFrom value) {
        this.objectSomeValuesFrom = value;
    }

    /**
     * Gets the value of the objectAllValuesFrom property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectAllValuesFrom }
     *     
     */
    public ObjectAllValuesFrom getObjectAllValuesFrom() {
        return objectAllValuesFrom;
    }

    /**
     * Sets the value of the objectAllValuesFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectAllValuesFrom }
     *     
     */
    public void setObjectAllValuesFrom(ObjectAllValuesFrom value) {
        this.objectAllValuesFrom = value;
    }

    /**
     * Gets the value of the objectHasValue property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectHasValue }
     *     
     */
    public ObjectHasValue getObjectHasValue() {
        return objectHasValue;
    }

    /**
     * Sets the value of the objectHasValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectHasValue }
     *     
     */
    public void setObjectHasValue(ObjectHasValue value) {
        this.objectHasValue = value;
    }

    /**
     * Gets the value of the objectHasSelf property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectHasSelf }
     *     
     */
    public ObjectHasSelf getObjectHasSelf() {
        return objectHasSelf;
    }

    /**
     * Sets the value of the objectHasSelf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectHasSelf }
     *     
     */
    public void setObjectHasSelf(ObjectHasSelf value) {
        this.objectHasSelf = value;
    }

    /**
     * Gets the value of the objectMinCardinality property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectMinCardinality }
     *     
     */
    public ObjectMinCardinality getObjectMinCardinality() {
        return objectMinCardinality;
    }

    /**
     * Sets the value of the objectMinCardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectMinCardinality }
     *     
     */
    public void setObjectMinCardinality(ObjectMinCardinality value) {
        this.objectMinCardinality = value;
    }

    /**
     * Gets the value of the objectMaxCardinality property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectMaxCardinality }
     *     
     */
    public ObjectMaxCardinality getObjectMaxCardinality() {
        return objectMaxCardinality;
    }

    /**
     * Sets the value of the objectMaxCardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectMaxCardinality }
     *     
     */
    public void setObjectMaxCardinality(ObjectMaxCardinality value) {
        this.objectMaxCardinality = value;
    }

    /**
     * Gets the value of the objectExactCardinality property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectExactCardinality }
     *     
     */
    public ObjectExactCardinality getObjectExactCardinality() {
        return objectExactCardinality;
    }

    /**
     * Sets the value of the objectExactCardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectExactCardinality }
     *     
     */
    public void setObjectExactCardinality(ObjectExactCardinality value) {
        this.objectExactCardinality = value;
    }

    /**
     * Gets the value of the dataSomeValuesFrom property.
     * 
     * @return
     *     possible object is
     *     {@link DataSomeValuesFrom }
     *     
     */
    public DataSomeValuesFrom getDataSomeValuesFrom() {
        return dataSomeValuesFrom;
    }

    /**
     * Sets the value of the dataSomeValuesFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSomeValuesFrom }
     *     
     */
    public void setDataSomeValuesFrom(DataSomeValuesFrom value) {
        this.dataSomeValuesFrom = value;
    }

    /**
     * Gets the value of the dataAllValuesFrom property.
     * 
     * @return
     *     possible object is
     *     {@link DataAllValuesFrom }
     *     
     */
    public DataAllValuesFrom getDataAllValuesFrom() {
        return dataAllValuesFrom;
    }

    /**
     * Sets the value of the dataAllValuesFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataAllValuesFrom }
     *     
     */
    public void setDataAllValuesFrom(DataAllValuesFrom value) {
        this.dataAllValuesFrom = value;
    }

    /**
     * Gets the value of the dataHasValue property.
     * 
     * @return
     *     possible object is
     *     {@link DataHasValue }
     *     
     */
    public DataHasValue getDataHasValue() {
        return dataHasValue;
    }

    /**
     * Sets the value of the dataHasValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataHasValue }
     *     
     */
    public void setDataHasValue(DataHasValue value) {
        this.dataHasValue = value;
    }

    /**
     * Gets the value of the dataMinCardinality property.
     * 
     * @return
     *     possible object is
     *     {@link DataMinCardinality }
     *     
     */
    public DataMinCardinality getDataMinCardinality() {
        return dataMinCardinality;
    }

    /**
     * Sets the value of the dataMinCardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataMinCardinality }
     *     
     */
    public void setDataMinCardinality(DataMinCardinality value) {
        this.dataMinCardinality = value;
    }

    /**
     * Gets the value of the dataMaxCardinality property.
     * 
     * @return
     *     possible object is
     *     {@link DataMaxCardinality }
     *     
     */
    public DataMaxCardinality getDataMaxCardinality() {
        return dataMaxCardinality;
    }

    /**
     * Sets the value of the dataMaxCardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataMaxCardinality }
     *     
     */
    public void setDataMaxCardinality(DataMaxCardinality value) {
        this.dataMaxCardinality = value;
    }

    /**
     * Gets the value of the dataExactCardinality property.
     * 
     * @return
     *     possible object is
     *     {@link DataExactCardinality }
     *     
     */
    public DataExactCardinality getDataExactCardinality() {
        return dataExactCardinality;
    }

    /**
     * Sets the value of the dataExactCardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataExactCardinality }
     *     
     */
    public void setDataExactCardinality(DataExactCardinality value) {
        this.dataExactCardinality = value;
    }

}
