//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 01:58:00 AM CET 
//


package org.w3._2002._07.owl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectHasValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectHasValue">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/2002/07/owl#}ClassExpression">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.w3.org/2002/07/owl#}ObjectPropertyExpression"/>
 *         &lt;group ref="{http://www.w3.org/2002/07/owl#}Individual"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectHasValue", propOrder = {
    "objectProperty",
    "objectInverseOf",
    "namedIndividual",
    "anonymousIndividual"
})
public class ObjectHasValue
    extends ClassExpression
{

    @XmlElement(name = "ObjectProperty")
    protected ObjectProperty objectProperty;
    @XmlElement(name = "ObjectInverseOf")
    protected ObjectInverseOf objectInverseOf;
    @XmlElement(name = "NamedIndividual")
    protected NamedIndividual namedIndividual;
    @XmlElement(name = "AnonymousIndividual")
    protected AnonymousIndividual anonymousIndividual;

    /**
     * Gets the value of the objectProperty property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectProperty }
     *     
     */
    public ObjectProperty getObjectProperty() {
        return objectProperty;
    }

    /**
     * Sets the value of the objectProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectProperty }
     *     
     */
    public void setObjectProperty(ObjectProperty value) {
        this.objectProperty = value;
    }

    /**
     * Gets the value of the objectInverseOf property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectInverseOf }
     *     
     */
    public ObjectInverseOf getObjectInverseOf() {
        return objectInverseOf;
    }

    /**
     * Sets the value of the objectInverseOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectInverseOf }
     *     
     */
    public void setObjectInverseOf(ObjectInverseOf value) {
        this.objectInverseOf = value;
    }

    /**
     * Gets the value of the namedIndividual property.
     * 
     * @return
     *     possible object is
     *     {@link NamedIndividual }
     *     
     */
    public NamedIndividual getNamedIndividual() {
        return namedIndividual;
    }

    /**
     * Sets the value of the namedIndividual property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedIndividual }
     *     
     */
    public void setNamedIndividual(NamedIndividual value) {
        this.namedIndividual = value;
    }

    /**
     * Gets the value of the anonymousIndividual property.
     * 
     * @return
     *     possible object is
     *     {@link AnonymousIndividual }
     *     
     */
    public AnonymousIndividual getAnonymousIndividual() {
        return anonymousIndividual;
    }

    /**
     * Sets the value of the anonymousIndividual property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnonymousIndividual }
     *     
     */
    public void setAnonymousIndividual(AnonymousIndividual value) {
        this.anonymousIndividual = value;
    }

}
