//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 01:58:00 AM CET 
//


package org.w3._2002._07.owl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectPropertyAxiom complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectPropertyAxiom">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/2002/07/owl#}Axiom">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectPropertyAxiom")
@XmlSeeAlso({
    TransitiveObjectProperty.class,
    IrreflexiveObjectProperty.class,
    DisjointObjectProperties.class,
    SubObjectPropertyOf.class,
    SymmetricObjectProperty.class,
    EquivalentObjectProperties.class,
    ObjectPropertyRange.class,
    InverseFunctionalObjectProperty.class,
    ObjectPropertyDomain.class,
    InverseObjectProperties.class,
    ReflexiveObjectProperty.class,
    AsymmetricObjectProperty.class,
    FunctionalObjectProperty.class
})
public abstract class ObjectPropertyAxiom
    extends Axiom
{


}
