//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 01:58:00 AM CET 
//


package org.w3._2002._07.owl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubDataPropertyOf complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubDataPropertyOf">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/2002/07/owl#}DataPropertyAxiom">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.w3.org/2002/07/owl#}DataPropertyExpression"/>
 *         &lt;group ref="{http://www.w3.org/2002/07/owl#}DataPropertyExpression"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubDataPropertyOf", propOrder = {
    "rest"
})
public class SubDataPropertyOf
    extends DataPropertyAxiom
{

    @XmlElementRef(name = "DataProperty", namespace = "http://www.w3.org/2002/07/owl#", type = JAXBElement.class, required = false)
    protected List<JAXBElement<DataProperty>> rest;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "DataProperty" is used by two different parts of a schema. See: 
     * line 227 of file:/I:/workspace/Wissensmodellierung/owlneo4j/owl.xsd
     * line 227 of file:/I:/workspace/Wissensmodellierung/owlneo4j/owl.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link DataProperty }{@code >}
     * 
     * 
     */
    public List<JAXBElement<DataProperty>> getRest() {
        if (rest == null) {
            rest = new ArrayList<JAXBElement<DataProperty>>();
        }
        return this.rest;
    }

}
