package uzuzjmd.competence.assessment.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserLearningTemplateMap service. Represents a row in the &quot;competenceAssessment_UserLearningTemplateMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link uzuzjmd.competence.assessment.model.impl.UserLearningTemplateMapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link uzuzjmd.competence.assessment.model.impl.UserLearningTemplateMapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserLearningTemplateMap
 * @see uzuzjmd.competence.assessment.model.impl.UserLearningTemplateMapImpl
 * @see uzuzjmd.competence.assessment.model.impl.UserLearningTemplateMapModelImpl
 * @generated
 */
public interface UserLearningTemplateMapModel extends BaseModel<UserLearningTemplateMap>,
    StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a user learning template map model instance should use the {@link UserLearningTemplateMap} interface instead.
     */

    /**
     * Returns the primary key of this user learning template map.
     *
     * @return the primary key of this user learning template map
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this user learning template map.
     *
     * @param primaryKey the primary key of this user learning template map
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this user learning template map.
     *
     * @return the uuid of this user learning template map
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this user learning template map.
     *
     * @param uuid the uuid of this user learning template map
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the user learning template map ID of this user learning template map.
     *
     * @return the user learning template map ID of this user learning template map
     */
    public long getUserLearningTemplateMapId();

    /**
     * Sets the user learning template map ID of this user learning template map.
     *
     * @param userLearningTemplateMapId the user learning template map ID of this user learning template map
     */
    public void setUserLearningTemplateMapId(long userLearningTemplateMapId);

    /**
     * Returns the group ID of this user learning template map.
     *
     * @return the group ID of this user learning template map
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this user learning template map.
     *
     * @param groupId the group ID of this user learning template map
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this user learning template map.
     *
     * @return the company ID of this user learning template map
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this user learning template map.
     *
     * @param companyId the company ID of this user learning template map
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this user learning template map.
     *
     * @return the user ID of this user learning template map
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this user learning template map.
     *
     * @param userId the user ID of this user learning template map
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this user learning template map.
     *
     * @return the user uuid of this user learning template map
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this user learning template map.
     *
     * @param userUuid the user uuid of this user learning template map
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this user learning template map.
     *
     * @return the user name of this user learning template map
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this user learning template map.
     *
     * @param userName the user name of this user learning template map
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this user learning template map.
     *
     * @return the create date of this user learning template map
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this user learning template map.
     *
     * @param createDate the create date of this user learning template map
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this user learning template map.
     *
     * @return the modified date of this user learning template map
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this user learning template map.
     *
     * @param modifiedDate the modified date of this user learning template map
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the learning template of this user learning template map.
     *
     * @return the learning template of this user learning template map
     */
    @AutoEscape
    public String getLearningTemplate();

    /**
     * Sets the learning template of this user learning template map.
     *
     * @param learningTemplate the learning template of this user learning template map
     */
    public void setLearningTemplate(String learningTemplate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(UserLearningTemplateMap userLearningTemplateMap);

    @Override
    public int hashCode();

    @Override
    public CacheModel<UserLearningTemplateMap> toCacheModel();

    @Override
    public UserLearningTemplateMap toEscapedModel();

    @Override
    public UserLearningTemplateMap toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
