package de.unipotsdam.elis.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.unipotsdam.elis.model.Evidence;
import de.unipotsdam.elis.service.EvidenceLocalServiceUtil;

/**
 * The extended model base implementation for the Evidence service. Represents a row in the &quot;UPServices_Evidence&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EvidenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EvidenceImpl
 * @see de.unipotsdam.elis.model.Evidence
 * @generated
 */
public abstract class EvidenceBaseImpl extends EvidenceModelImpl
    implements Evidence {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a evidence model instance should use the {@link Evidence} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EvidenceLocalServiceUtil.addEvidence(this);
        } else {
            EvidenceLocalServiceUtil.updateEvidence(this);
        }
    }
}
