package de.unipotsdam.elis.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import de.unipotsdam.elis.model.Evidence;
import de.unipotsdam.elis.service.EvidenceService;
import de.unipotsdam.elis.service.persistence.EvidencePersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the evidence remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link de.unipotsdam.elis.service.impl.EvidenceServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see de.unipotsdam.elis.service.impl.EvidenceServiceImpl
 * @see de.unipotsdam.elis.service.EvidenceServiceUtil
 * @generated
 */
public abstract class EvidenceServiceBaseImpl extends BaseServiceImpl
    implements EvidenceService, IdentifiableBean {
    @BeanReference(type = de.unipotsdam.elis.service.EvidenceLocalService.class)
    protected de.unipotsdam.elis.service.EvidenceLocalService evidenceLocalService;
    @BeanReference(type = de.unipotsdam.elis.service.EvidenceService.class)
    protected de.unipotsdam.elis.service.EvidenceService evidenceService;
    @BeanReference(type = EvidencePersistence.class)
    protected EvidencePersistence evidencePersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private EvidenceServiceClpInvoker _clpInvoker = new EvidenceServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link de.unipotsdam.elis.service.EvidenceServiceUtil} to access the evidence remote service.
     */

    /**
     * Returns the evidence local service.
     *
     * @return the evidence local service
     */
    public de.unipotsdam.elis.service.EvidenceLocalService getEvidenceLocalService() {
        return evidenceLocalService;
    }

    /**
     * Sets the evidence local service.
     *
     * @param evidenceLocalService the evidence local service
     */
    public void setEvidenceLocalService(
        de.unipotsdam.elis.service.EvidenceLocalService evidenceLocalService) {
        this.evidenceLocalService = evidenceLocalService;
    }

    /**
     * Returns the evidence remote service.
     *
     * @return the evidence remote service
     */
    public de.unipotsdam.elis.service.EvidenceService getEvidenceService() {
        return evidenceService;
    }

    /**
     * Sets the evidence remote service.
     *
     * @param evidenceService the evidence remote service
     */
    public void setEvidenceService(
        de.unipotsdam.elis.service.EvidenceService evidenceService) {
        this.evidenceService = evidenceService;
    }

    /**
     * Returns the evidence persistence.
     *
     * @return the evidence persistence
     */
    public EvidencePersistence getEvidencePersistence() {
        return evidencePersistence;
    }

    /**
     * Sets the evidence persistence.
     *
     * @param evidencePersistence the evidence persistence
     */
    public void setEvidencePersistence(EvidencePersistence evidencePersistence) {
        this.evidencePersistence = evidencePersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Evidence.class;
    }

    protected String getModelClassName() {
        return Evidence.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = evidencePersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
