package uzuzjmd.competence.persistence.ontology;

/**
 *
 */
public enum Edge {
    MetaCatchwordOf,
    SubCompetenceOf,
    SubOperatorOf,
    OperatorOf,
    CatchwordOf,
    EvidencOf,
    CompetenceDescriptionOf,
    DescriptionElementOf,
    BelongsToArea,
    HasCompetence,
    SpecifiedBy,
    LearnerOf,
    MetaOperatorOf,
    CourseContextOfCompetence,
    CompulsoryOf,
    CommentOf,
    LinkOfCourseContext,
    UserOfLink,
    ActivityOf,
    createdBy,
    UserOfComment,
    linksCompetence,
    PrerequisiteOf,
    NotPrerequisiteOf,
    NotAllowedToView,
    SuggestedCompetencePrerequisiteOf,
    LearningProjectTemplateOf,
    CourseContextOfSelectedLearningProjectTemplate,
    UserOfLearningProjectTemplate,
    AssessmentOfUser,
    AssessmentOfCompetence,
    UserHasPerformed,
    SuggestedActivityForCompetence,
    RecommendedCourseForUser,
    subClassOf,
    CourseContextOfUser
}
