package de.unipotsdam.elis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Evidence service. Represents a row in the &quot;UPServices_Evidence&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.unipotsdam.elis.model.impl.EvidenceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.unipotsdam.elis.model.impl.EvidenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Evidence
 * @see de.unipotsdam.elis.model.impl.EvidenceImpl
 * @see de.unipotsdam.elis.model.impl.EvidenceModelImpl
 * @generated
 */
public interface EvidenceModel extends BaseModel<Evidence>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a evidence model instance should use the {@link Evidence} interface instead.
     */

    /**
     * Returns the primary key of this evidence.
     *
     * @return the primary key of this evidence
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this evidence.
     *
     * @param primaryKey the primary key of this evidence
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the evidence ID of this evidence.
     *
     * @return the evidence ID of this evidence
     */
    public long getEvidenceId();

    /**
     * Sets the evidence ID of this evidence.
     *
     * @param evidenceId the evidence ID of this evidence
     */
    public void setEvidenceId(long evidenceId);

    /**
     * Returns the group ID of this evidence.
     *
     * @return the group ID of this evidence
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this evidence.
     *
     * @param groupId the group ID of this evidence
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this evidence.
     *
     * @return the company ID of this evidence
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this evidence.
     *
     * @param companyId the company ID of this evidence
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this evidence.
     *
     * @return the user ID of this evidence
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this evidence.
     *
     * @param userId the user ID of this evidence
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this evidence.
     *
     * @return the user uuid of this evidence
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this evidence.
     *
     * @param userUuid the user uuid of this evidence
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this evidence.
     *
     * @return the user name of this evidence
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this evidence.
     *
     * @param userName the user name of this evidence
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this evidence.
     *
     * @return the create date of this evidence
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this evidence.
     *
     * @param createDate the create date of this evidence
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this evidence.
     *
     * @return the modified date of this evidence
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this evidence.
     *
     * @param modifiedDate the modified date of this evidence
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the title of this evidence.
     *
     * @return the title of this evidence
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this evidence.
     *
     * @param title the title of this evidence
     */
    public void setTitle(String title);

    /**
     * Returns the link of this evidence.
     *
     * @return the link of this evidence
     */
    @AutoEscape
    public String getLink();

    /**
     * Sets the link of this evidence.
     *
     * @param link the link of this evidence
     */
    public void setLink(String link);

    /**
     * Returns the summary of this evidence.
     *
     * @return the summary of this evidence
     */
    @AutoEscape
    public String getSummary();

    /**
     * Sets the summary of this evidence.
     *
     * @param summary the summary of this evidence
     */
    public void setSummary(String summary);

    /**
     * Returns the activity typ of this evidence.
     *
     * @return the activity typ of this evidence
     */
    @AutoEscape
    public String getActivityTyp();

    /**
     * Sets the activity typ of this evidence.
     *
     * @param activityTyp the activity typ of this evidence
     */
    public void setActivityTyp(String activityTyp);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Evidence evidence);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Evidence> toCacheModel();

    @Override
    public Evidence toEscapedModel();

    @Override
    public Evidence toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
