package uzuzjmd.competence.service.soap.jaxws;

import javax.xml.bind.annotation.XmlElement;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2 Wed Feb 26 14:16:33
 * CET 2014 Generated source version: 3.0.0-milestone2
 */

// @XmlRootElement(name = "insertCompetence", namespace =
// "http://competence.service.uzuzjmd/")
// @XmlAccessorType(XmlAccessType.FIELD)
// @XmlType(name = "insertCompetence", namespace =
// "http://competence.service.uzuzjmd/")

public class InsertCompetence {

	@XmlElement(name = "arg0")
	private uzuzjmd.competence.rcd.generated.Rdceo arg0;

	public uzuzjmd.competence.rcd.generated.Rdceo getArg0() {
		return this.arg0;
	}

	public void setArg0(uzuzjmd.competence.rcd.generated.Rdceo newArg0) {
		this.arg0 = newArg0;
	}

}
