package uzuzjmd.competence.service.soap.jaxws;


/**
 * This class was generated by Apache CXF 3.0.0-milestone2 Wed Feb 26 14:16:33
 * CET 2014 Generated source version: 3.0.0-milestone2
 */

// @XmlRootElement(name = "insertCompetenceResponse", namespace =
// "http://competence.service.uzuzjmd/")
// @XmlAccessorType(XmlAccessType.FIELD)
// @XmlType(name = "insertCompetenceResponse", namespace =
// "http://competence.service.uzuzjmd/")

public class InsertCompetenceResponse {

}
