package uzuzjmd.competence.owl.ontology;

public enum CompObjectProperties {
	SimilarTo,
	SubCompetenceOf,
	SubOperatorOf,
	OperatorOf,
	CatchwordOf,
	MetaCatchwordOf,	
	EvidencOf,		
	CompetenceDescriptionOf,
	DescriptionElementOf,
	BelongsToArea,	
	HasCompetence,
	SpecifiedBy,
	LearnerOf,
	requiredFor,	
	LearnerOfInverse,
	CatchwordOfInverse,
	OperatorOfInverse,
	SimilarToInverse,
	SubCompetenceOfInverse,
	SubOperatorOfInverse,	
	MetaCatchwordOfInverse,	
	EvidencOfInverse,		
	CompetenceDescriptionOfInverse,
	DescriptionElementOfInverse,
	BelongsToAreaInverse,	
	HasCompetenceInverse,
	SpecifiedByInverse,	
	requiredForInverse
}
